version: '3.8'

services:
  # 1. 初期化コンテナ
  initializer:
    build: ./initializer
    volumes:
      - symbol_startup_v3:/app/dest_startup       # 👈 _v3 に更新
      - symbol_userconfig_v3:/app/dest_userconfig # 👈 _v3 に更新
      - symbol_mongo_v3:/app/dest_mongo           # 👈 _v3 に更新
    environment:
      - SYMBOL_NETWORK=${SYMBOL_NETWORK:-mainnet}
      - NODE_NAME=${NODE_NAME:-MyDokployNode}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - MAIN_PRIVATE_KEY=${MAIN_PRIVATE_KEY}
      - VRF_PRIVATE_KEY=${VRF_PRIVATE_KEY}
      - REMOTE_PRIVATE_KEY=${REMOTE_PRIVATE_KEY}
      - VOTING_PRIVATE_KEY=${VOTING_PRIVATE_KEY}
    networks:
      - dokploy-network

  # 2. MongoDB
  db:
    image: mongo:7.0.23
    command: mongod --replSet rs0 --bind_ip_all
    volumes:
      - mongodb_data_v3:/data/db # 👈 _v3 に更新
    restart: always
    networks:
      - dokploy-network

  # 3. MongoDB レプリカセット初期化タスク
  mongo-init:
    image: mongo:7.0.23
    user: root
    entrypoint: ["/bin/bash", "-c"] # 👈 配列形式でイメージの挙動を完全抹殺
    depends_on:
      - db
    volumes:
      - symbol_startup_v3:/startup:ro # 👈 _v3 に更新
    command: "/bin/bash /startup/mongors.sh"
    networks:
      - dokploy-network

  # 4. Symbol Broker
  broker:
    image: symbolplatform/symbol-server:gcc-1.0.3.9
    user: root
    entrypoint: ["/bin/bash", "-c"] # 👈 配列形式でイメージの挙動を完全抹殺
    depends_on:
      - initializer
      - db
    volumes:
      - symbol_startup_v3:/startup:ro       # 👈 _v3 に更新
      - symbol_userconfig_v3:/userconfig:ro # 👈 _v3 に更新
      - symbol_data_v3:/data                # 👈 _v3 に更新
    command: "/bin/bash /startup/startBroker.sh /userconfig"
    restart: always
    networks:
      - dokploy-network

  # 5. Symbol ノード本体
  node:
    image: symbolplatform/symbol-server:gcc-1.0.3.9
    user: root
    entrypoint: ["/bin/bash", "-c"] # 👈 配列形式でイメージの挙動を完全抹殺
    depends_on:
      - initializer
      - broker
    volumes:
      - symbol_startup_v3:/startup:ro       # 👈 _v3 に更新
      - symbol_userconfig_v3:/userconfig:ro # 👈 _v3 に更新
      - symbol_data_v3:/data                # 👈 _v3 に更新
    ports:
      - "7900:7900"
    command: "/bin/bash /startup/startServer.sh /userconfig"
    restart: always
    networks:
      - dokploy-network

  # 6. REST ゲートウェイ
  rest-gateway:
    image: symbolplatform/symbol-rest:2.5.1
    user: root
    entrypoint: ["/bin/bash", "-c"] # 👈 配列形式でイメージの挙動を完全抹殺
    depends_on:
      - node
      - db
    volumes:
      - symbol_startup_v3:/startup:ro       # 👈 _v3 に更新
      - symbol_userconfig_v3:/userconfig:ro # 👈 _v3 に更新
    ports:
      - "3000:3000"
    command: "/bin/bash /startup/delayrestapi.sh /userconfig"
    restart: always
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true

# すべて末尾を _v3 にリフレッシュ
volumes:
  symbol_startup_v3:
  symbol_userconfig_v3:
  symbol_mongo_v3:
  symbol_data_v3:
  mongodb_data_v3: