version: '3.8'

services:
  # 1. 初期化コンテナ
  initializer:
    build: ./initializer
    volumes:
      - symbol_config:/app/target
    environment:
      - SYMBOL_NETWORK=${SYMBOL_NETWORK:-mainnet}
      - NODE_NAME=${NODE_NAME:-MyDokployNode}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - MAIN_PRIVATE_KEY=${MAIN_PRIVATE_KEY}
      - VRF_PRIVATE_KEY=${VRF_PRIVATE_KEY}
      - REMOTE_PRIVATE_KEY=${REMOTE_PRIVATE_KEY}
      - VOTING_PRIVATE_KEY=${VOTING_PRIVATE_KEY}
    networks:
      - dokploy-network

  # 2. MongoDB
  db:
    image: mongo:7.0.23
    command: mongod --replSet rs0 --bind_ip_all
    volumes:
      - mongodb_data:/data/db
    restart: always
    networks:
      - dokploy-network

  # 3. MongoDB レプリカセット初期化タスク
  mongo-init:
    image: mongo:7.0.23
    user: root # 👇 ここを追加
    depends_on:
      - db
    volumes:
      - symbol_config:/symbol:ro
    command: /bin/bash /symbol/startup/mongors.sh
    networks:
      - dokploy-network

  # 4. Symbol Broker
  broker:
    image: symbolplatform/symbol-server:gcc-1.0.3.9
    user: root # 👇 ここを追加
    command: /bin/bash /symbol/startup/startBroker.sh /symbol/userconfig
    depends_on:
      - initializer
      - db
    volumes:
      - symbol_config:/symbol:ro
      - symbol_data:/data
    restart: always
    networks:
      - dokploy-network

  # 5. Symbol ノード本体
  node:
    image: symbolplatform/symbol-server:gcc-1.0.3.9
    user: root # 👇 ここを追加
    command: /bin/bash /symbol/startup/startServer.sh /symbol/userconfig
    depends_on:
      - initializer
      - broker
    volumes:
      - symbol_config:/symbol:ro
      - symbol_data:/data
    ports:
      - "7900:7900"
    restart: always
    networks:
      - dokploy-network

  # 6. REST ゲートウェイ
  rest-gateway:
    image: symbolplatform/symbol-rest:2.5.1
    user: root # 👇 ここを追加
    command: /bin/bash /symbol/startup/delayrestapi.sh /symbol/userconfig
    depends_on:
      - node
      - db
    volumes:
      - symbol_config:/symbol:ro
    ports:
      - "3000:3000"
    restart: always
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true

volumes:
  symbol_config:
  symbol_data:
  mongodb_data: